-- Clean first draft, just drops schema.

DROP SCHEMA IF EXISTS `qubaccomodation48`;
CREATE SCHEMA IF NOT EXISTS `qubaccomodation48`;
DROP TABLE IF EXISTS Buildings;
DROP TABLE IF EXISTS Apartment;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Tenant;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Manager;
DROP TABLE IF EXISTS TechnicianSkill;
DROP TABLE IF EXISTS Skill;
DROP TABLE IF EXISTS Lease;
DROP TABLE IF EXISTS LeaseTenant;
