insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Baryram', 'Caygill', 'Steffen', '8252896523', 'Mother', '7625912190');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Xylia', 'Helsdon', 'Dorian', '6454776690', 'Father', '2764059300');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Paten', 'Dofty', 'Garvin', '9754364958', 'Mother', '7415268862');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Mitzi', 'Tuckie', 'Sydney', '7025483721', 'Father', '9152344654');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Prudence', 'Raxworthy', 'Ingeberg', '1786672900', 'Father', '2223413033');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Luci', 'Chrishop', 'Chanda', '1508553533', 'Father', '6476626987');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gavan', 'Folliss', 'Gene', '4671404253', 'Mother', '1085594355');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lanie', 'Kupec', 'Julian', '3494103162', 'Cousin', '8158313644');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Tedmund', 'Bartusek', 'Thedrick', '5868080224', 'Mother', '4882882626');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Darlleen', 'Murricanes', 'Kathrine', '3326703621', 'Father', '5052423081');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Alica', 'Senter', 'Pansie', '6911427495', 'Father', '5402499471');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Maryanne', 'Duffill', 'Quintilla', '1299854560', 'Father', '3254276421');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kimberlyn', 'Farriar', 'Marylee', '4928772514', 'Father', '7417020177');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Marion', 'Papaccio', 'Rick', '8702834344', 'Mother', '1034943404');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Raimund', 'Cosans', 'Louis', '9578565502', 'Brother', '6668888849');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Ash', 'Hane', 'Wolfgang', '4389127474', 'Mother', '4666692380');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Garvey', 'De Miranda', 'Izak', '8004571558', 'Sister', '3611760577');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Norby', 'Presman', 'Burt', '5025974776', 'Mother', '7526532728');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lacee', 'Lazar', 'Trudi', '9011877671', 'Father', '3488165211');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Demetria', 'Joskovitch', 'Malinde', '2186427912', 'Father', '5138705713');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Marilin', 'Ginn', 'Audy', '6815970666', 'Father', '5788774852');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Calli', 'Beeke', 'Sadie', '5969490626', 'Father', '2948145359');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Cecilla', 'Dudson', 'Emylee', '9293198132', 'Father', '5103139192');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Estella', 'Klimkov', 'Ronnica', '8981193000', 'Brother', '3431911663');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Hyman', 'Taberer', 'Purcell', '7113014110', 'Guardian', '4712838311');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Vincenty', 'Caustic', 'Tymon', '2135629375', 'Mother', '4775661507');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gradeigh', 'Drakeford', 'Alick', '6473055710', 'Mother', '9417960825');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kiley', 'Cleave', 'Barrie', '8208572267', 'Mother', '6195000413');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gordy', 'Beattie', 'Bryanty', '8418900163', 'Mother', '4961621684');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Melessa', 'Grimmer', 'Rhonda', '1937579560', 'Father', '8628530471');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lorrie', 'Acey', 'Katuscha', '7262021915', 'Father', '9362032301');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Darell', 'Hardingham', 'Carissa', '2046416677', 'Father', '1022900043');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Mallorie', 'Twydell', 'Teddy', '8239258937', 'Uncle', '1847122186');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Maressa', 'MacCole', 'Zoe', '6679068855', 'Guardian', '8444893520');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Brad', 'Benjamin', 'Christopher', '3614526761', 'Mother', '6928616958');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Virgie', 'Kintish', 'Jeffy', '9735626300', 'Mother', '1208605556');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Booth', 'Carder', 'Chalmers', '4288856011', 'Mother', '9374977603');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Wait', 'Yakunin', 'Rawley', '5478722575', 'Mother', '1952692687');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Roze', 'Barlace', 'Meagan', '5492912180', 'Father', '1938757648');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Xymenes', 'Grimshaw', 'Bryan', '4253891237', 'Mother', '6513565631');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Ambros', 'Fruish', 'Torin', '3489243760', 'Mother', '7457066843');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Shauna', 'Newcombe', 'Vonnie', '2631890928', 'Uncle', '6494403734');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gregory', 'Llewhellin', 'Morten', '5201531584', 'Mother', '3097845682');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Vanya', 'Pavelka', 'Jessamyn', '9372554133', 'Sister', '8046501054');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Domenic', 'Mac Giany', 'Zacharia', '1707168780', 'Mother', '4942164004');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bartlett', 'Heald', 'Chico', '9085111301', 'Mother', '4988002733');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Reinaldo', 'Keune', 'Martino', '2994769673', 'Mother', '7281239693');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gray', 'Gunda', 'Yancy', '3404557014', 'Mother', '7932661358');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lois', 'Russell', 'Jessy', '4471604016', 'Father', '6893119152');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Paddie', 'Vasishchev', 'Shaw', '8629933746', 'Uncle', '6572771291');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Adrien', 'McCallam', 'Hy', '5353471944', 'Mother', '8397451183');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Jemimah', 'Bilyard', 'Carline', '6539904673', 'Father', '3147608962');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Nicky', 'Gon', 'Elnore', '8849233357', 'Father', '2951050305');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bernardo', 'Moden', 'Martin', '6634255213', 'Mother', '5774422308');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Celestyn', 'Kenna', 'Josee', '6332732995', 'Father', '2746029165');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Dacy', 'MacGill', 'Regine', '1592068981', 'Father', '5343070493');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bren', 'Bonny', 'Ninette', '3298190664', 'Guardian', '2196252275');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Henrieta', 'Pennuzzi', 'Corrine', '6937230354', 'Father', '2354855343');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Dianemarie', 'Sidney', 'Elyssa', '8277903589', 'Father', '3653610342');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Teodorico', 'Jeandillou', 'Allan', '2375260605', 'Uncle', '2311285088');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Freeland', 'Tatton', 'Ogden', '6041235247', 'Mother', '3794349453');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Heinrik', 'Spittles', 'Montague', '8462505807', 'Mother', '4521366766');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Jillayne', 'Mussetti', 'Belvia', '1027315141', 'Brother', '4848054096');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lowe', 'Legen', 'Royal', '5909137717', 'Mother', '9151620341');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Elisabet', 'Berge', 'Sib', '2802951810', 'Father', '3891331265');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Jenni', 'Salvadori', 'Elfrieda', '9751598435', 'Father', '9243060944');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bailie', 'Ainscow', 'Garik', '7001271212', 'Mother', '2953679025');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Vivian', 'Eckert', 'Randi', '5106953097', 'Father', '2295779654');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lonna', 'Derrington', 'Giselle', '4306285654', 'Uncle', '9163469875');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Derrick', 'Fraanchyonok', 'Sollie', '3287239018', 'Mother', '1058725863');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Cassie', 'Smitten', 'Karoly', '5132526969', 'Mother', '6803058278');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Nadya', 'Highway', 'Beverlie', '5795131601', 'Guardian', '5573134579');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Guglielma', 'Bromage', 'Lorinda', '4985331545', 'Father', '7705443526');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Jerrilyn', 'Maymond', 'Clea', '1639608885', 'Father', '5549793484');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Adamo', 'Males', 'Calv', '8218565247', 'Mother', '2599955597');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Obidiah', 'Ryde', 'Stefan', '1242598291', 'Mother', '2808298485');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Humberto', 'Dumphries', 'Oswald', '3349484746', 'Mother', '7877715386');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Antony', 'Piscotti', 'Warner', '5605082514', 'Uncle', '3625979363');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Arley', 'Neame', 'Penny', '8564171449', 'Mother', '8869554171');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Welch', 'Goosey', 'Hale', '8997746344', 'Mother', '2622823193');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Adlai', 'Paulitschke', 'Terrill', '2715117669', 'Mother', '9484802661');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Jo-anne', 'Hauxley', 'Corie', '1133630168', 'Father', '5844478420');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bryna', 'Bagguley', 'Ivy', '1338286603', 'Father', '4035456195');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Evey', 'Langman', 'Adella', '3922004284', 'Guardian', '5305529057');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Ashlie', 'Galilee', 'Dael', '4143971233', 'Uncle', '6837540179');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Clarita', 'Ligertwood', 'Olive', '6291077688', 'Father', '8026724994');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Del', 'Ruller', 'Jerad', '9649750641', 'Mother', '9382317747');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Sibilla', 'Balloch', 'Felecia', '5217169094', 'Father', '6855135870');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gelya', 'Yepiskopov', 'Carlin', '7315249186', 'Father', '3183954173');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Layla', 'Draper', 'Audi', '6352566063', 'Father', '7355625075');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Burnard', 'Henner', 'Tuckie', '8059984576', 'Mother', '3816842327');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gabriele', 'Scargle', 'Berny', '4281244314', 'Sister', '1754336315');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Karoly', 'Mc Coughan', 'Jdavie', '7957753892', 'Mother', '4529873757');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kristofer', 'Avann', 'Brander', '5455645822', 'Uncle', '3501385741');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Auguste', 'Ixer', 'Sianna', '9223648896', 'Father', '5192922368');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Aigneis', 'Fidilis', 'Dolley', '3571568968', 'Father', '1111408611');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Chris', 'Trathan', 'Bonny', '7817209955', 'Father', '8924228444');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Griselda', 'Tyhurst', 'Sheri', '2821882381', 'Father', '6582285622');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Mabelle', 'Hatcher', 'Katherina', '2686131954', 'Sister', '7229111294');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Dayna', 'Challicum', 'Darsey', '6077004311', 'Father', '1575969428');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Mischa', 'Baraja', 'Pierson', '2208683920', 'Mother', '2956298538');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Zoe', 'Tripe', 'Melloney', '5312522446', 'Father', '5434321768');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Benjamen', 'Kinneir', 'Jeromy', '9874127306', 'Mother', '2791251702');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Faustina', 'Dallyn', 'Beryl', '8511161548', 'Father', '5262974172');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Abdel', 'Cassimer', 'Owen', '7335405097', 'Mother', '3222822287');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Yolanthe', 'Bimson', 'Aubree', '2946002785', 'Father', '1799045833');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Albina', 'Perin', 'Cherin', '5307253442', 'Father', '1356124998');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Cinderella', 'Markova', 'Genevieve', '2579108935', 'Father', '5487386025');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kittie', 'Eteen', 'Sherry', '6348018732', 'Father', '7005841112');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lennard', 'Arnopp', 'Tiler', '3029050066', 'Mother', '9654885762');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bjorn', 'Frossell', 'Michail', '4971673217', 'Mother', '4724568174');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kelvin', 'Matveyev', 'Maxwell', '6263197401', 'Guardian', '2427205882');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Fawne', 'Mytton', 'Devora', '2999460935', 'Father', '4067110796');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Giovanni', 'Fideler', 'Morton', '5194324948', 'Mother', '5852845394');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kesley', 'Crissil', 'Jenni', '6782683443', 'Father', '5393792641');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Waring', 'Cannam', 'Baxy', '3373860706', 'Mother', '8216165873');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Hewett', 'Dessant', 'Colin', '7801185036', 'Uncle', '5663167053');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Karine', 'Millins', 'Devinne', '7136163653', 'Father', '9732784756');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kinnie', 'Cutajar', 'Gaven', '8376293315', 'Mother', '7456502515');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Giustino', 'Laycock', 'Neville', '5654682569', 'Mother', '5769402994');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Barnaby', 'Stonard', 'Justinian', '6533969323', 'Mother', '4949043066');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Conant', 'Rivett', 'Francklin', '8264634790', 'Mother', '9049357934');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Queenie', 'Trewin', 'Loni', '1978299973', 'Sister', '2928568292');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Micheal', 'Andreix', 'Herc', '4353707675', 'Mother', '2609041950');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Stefanie', 'Kobierski', 'Christabel', '4264120192', 'Father', '2017147307');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Myrlene', 'Mangeney', 'Cordy', '7254620423', 'Father', '9362304762');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Shepperd', 'Dalwood', 'Stanton', '6408419225', 'Mother', '1052583717');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Janeen', 'Edgeworth', 'Angelika', '6076303558', 'Father', '2328335757');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Arlette', 'Hadlington', 'Flore', '5332068436', 'Father', '8281525349');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Alexina', 'Trorey', 'Katina', '5154337686', 'Father', '3847725875');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Enos', 'Yarham', 'Ralf', '2238404166', 'Guardian', '9524147397');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Huntington', 'Dechelette', 'Harbert', '9879826275', 'Mother', '3717648558');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lenard', 'Sarfass', 'Ezequiel', '2414401392', 'Mother', '2281891851');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Tom', 'Beausang', 'Gardy', '5811095073', 'Mother', '6138152002');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kiley', 'Attrie', 'Nannie', '6099619625', 'Father', '1119774095');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Ruth', 'Stallworthy', 'Carmelina', '4429347307', 'Father', '7301300912');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Mellisa', 'Godbold', 'Kaylil', '2708453814', 'Father', '6997482824');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Ruthi', 'Esterbrook', 'Terrie', '7779223650', 'Father', '1811060889');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Giustina', 'Trosdall', 'Darell', '4624102200', 'Guardian', '9828900445');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Florentia', 'Mildner', 'Gigi', '1116412193', 'Father', '2306633693');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Minta', 'Senechell', 'Druci', '6791811740', 'Father', '1174396335');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Alvie', 'Downey', 'Ettore', '6823563825', 'Mother', '4562839479');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gael', 'Reffe', 'Kai', '3461712826', 'Father', '6025415614');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bab', 'Arntzen', 'Victoria', '8834098314', 'Father', '6394685861');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Belicia', 'Jeffels', 'Haleigh', '1072649987', 'Father', '9334030319');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kristan', 'McEwan', 'Mada', '2823073900', 'Father', '5971767081');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Melva', 'Tussaine', 'Sara-ann', '9863007819', 'Father', '5047912322');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Daveta', 'Renon', 'Adelaide', '8391208378', 'Father', '3473206873');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kirby', 'Keppie', 'Cornell', '7986939170', 'Mother', '6195626184');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Sean', 'Cearley', 'Yankee', '5084955922', 'Mother', '9996395823');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Katlin', 'Rohloff', 'Sarena', '1796345654', 'Brother', '3796360442');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Morris', 'Silversmid', 'Frederik', '1569770857', 'Mother', '1105159203');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Nady', 'Bath', 'Eran', '7255857421', 'Father', '6854663480');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Roy', 'Tie', 'Germain', '4439363455', 'Mother', '6887154912');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Norma', 'Frostdicke', 'Ellene', '2553453213', 'Father', '3123503600');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Karine', 'MacMorland', 'Vilhelmina', '2304522084', 'Father', '3725101173');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Nedda', 'Vallentine', 'Adina', '5754586545', 'Father', '2642617898');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Allyn', 'Alf', 'Osborn', '9947269401', 'Mother', '3193670634');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Jacquette', 'Heinig', 'Wallis', '3913744549', 'Father', '3727222064');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lexi', 'Hallibone', 'Kary', '8997776135', 'Father', '9454840632');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kori', 'Tinkler', 'L;urette', '7667539037', 'Father', '2948067071');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Orson', 'Lief', 'Brig', '2243253354', 'Mother', '9868042221');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Cilka', 'Dalley', 'Coreen', '2449393780', 'Father', '6868614357');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Virginie', 'Buckenham', 'Gelya', '5227009087', 'Father', '4344620835');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Silvester', 'Avramchik', 'Nathanil', '2641625540', 'Mother', '9088502952');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Westbrooke', 'Dressel', 'Palmer', '4757454593', 'Mother', '1544851592');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Edwina', 'Matzeitis', 'Deny', '5554458977', 'Father', '1954517954');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Babara', 'Riping', 'Wally', '5842735144', 'Father', '5527345351');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kile', 'O''Teague', 'Claudio', '3668724413', 'Mother', '6715998011');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bondon', 'Radnage', 'Sigmund', '5635702588', 'Mother', '5226067267');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Rupert', 'Mulholland', 'Noe', '4758078664', 'Mother', '5085202035');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Quentin', 'Birdwistle', 'Emmy', '2286108815', 'Mother', '9911751217');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Marietta', 'Fosse', 'Reed', '2757187944', 'Mother', '7699889779');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Hyman', 'Cuttles', 'Kendrick', '1222045929', 'Mother', '2597008803');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Abeu', 'Nudds', 'Stinky', '2666723434', 'Mother', '9763980598');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bertie', 'Greenshields', 'Berny', '1591547111', 'Mother', '1449577711');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Ulrike', 'Calken', 'Othelia', '8779037359', 'Father', '9612104631');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Albrecht', 'Cowing', 'Wallache', '7763160669', 'Uncle', '3163422958');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Morton', 'Sims', 'Gerri', '4578333307', 'Mother', '7846624135');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Brigitte', 'Mungane', 'Melodie', '9769340369', 'Father', '1359519220');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Lazaro', 'Worden', 'Brock', '6779662480', 'Mother', '4659178937');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Kristal', 'Garnall', 'Livvy', '4338882537', 'Father', '3153862444');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Loria', 'Bourdon', 'Betteann', '8063964653', 'Father', '8757035546');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Cherida', 'Lafranconi', 'Reiko', '9061275449', 'Father', '3645582866');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Darrelle', 'Croad', 'Rhianna', '6887595164', 'Father', '7815141450');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Darrell', 'Blewmen', 'Zebadiah', '9189529047', 'Mother', '1589075016');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bil', 'Mainland', 'Gabbie', '7681745486', 'Mother', '3597500120');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Chad', 'Manilo', 'Kerstin', '7581548106', 'Father', '1868028261');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Pat', 'Phillimore', 'Sunshine', '4485759275', 'Father', '7324168762');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Aloysius', 'Manby', 'Allie', '6741650315', 'Mother', '4075274179');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Thadeus', 'Lemerie', 'Kippie', '1838513630', 'Brother', '9251916542');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Jasmina', 'Iddins', 'Mavra', '1151579852', 'Father', '7833952303');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Corrie', 'Bolf', 'Carry', '7638771091', 'Father', '6525069313');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Alma', 'Fritchly', 'Shayla', '3853992674', 'Father', '4733917211');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Glory', 'Farnorth', 'Drusi', '3253165239', 'Father', '7902423755');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Fancy', 'Noods', 'Coralyn', '3176135275', 'Father', '1814167640');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Arvie', 'Northall', 'Dallas', '2573107172', 'Mother', '1856574822');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Udall', 'Grier', 'Hubie', '6695841748', 'Mother', '9015273956');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bryan', 'Mathieu', 'Nevin', '4061896747', 'Mother', '1835236509');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Zachariah', 'Breese', 'Padgett', '7507658879', 'Mother', '1195134464');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Marlane', 'Chattoe', 'Krissy', '3689478917', 'Wife', '7486924953');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Arden', 'Coppock.', 'Maiga', '2927274733', 'Sister', '9134397809');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Letisha', 'Chown', 'Emmalee', '5244065554', 'Brother', '5715366111');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Gordan', 'Gockelen', 'Lemmie', '8223266567', 'Father', '1301580265');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Aeriel', 'Toon', 'Janet', '4702333967', 'Father', '9773053841');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Yvonne', 'Tomasz', 'Angy', '3698645153', 'Father', '3741149991');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Cheri', 'Pendleberry', 'Fan', '9936395969', 'Guardian', '1387612233');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Anjela', 'Margrett', 'Courtney', '5894568959', 'Husband', '1483914680');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Libby', 'Kingaby', 'Palmer', '4237251304', 'Wife', '9309156555');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Farrah', 'Throughton', 'Lanna', '6172830431', 'Wife', '4522235481');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bear', 'Hatrey', 'Tine', '1461876705', 'Husband', '1405411803');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Bee', 'Martindale', 'Alina', '2344896231', 'Wife', '1077683836');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Enriqueta', 'Sissens', 'Morgan', '8966619013', 'Mother', '8588658272');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Joaquin', 'Gurnay', 'Melly', '6316524666', 'Guardian', '2333301293');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Laurie', 'Wathen', 'Anett', '7397324105', 'Husband', '5891431564');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Darren', 'Essam', 'Reinwald', '2062334799', 'Wife', '8558314514');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Neille', 'Maundrell', 'Heindrick', '8976245279', 'Cousin', '5185579712');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Wit', 'Trevett', 'Stanislaus', '2485864354', 'Cousin', '7843471454');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Joshuah', 'Karpman', 'Aleksandr', '9825390779', 'Father', '3991876086');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Aindrea', 'Laight', 'Britney', '1665293002', 'Mother', '4401581442');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Rodrique', 'Menichini', 'Imojean', '3698199609', 'Cousin', '9419692333');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Urbano', 'Rames', 'Mortie', '4986134764', 'Wife', '4913471323');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Ealasaid', 'Florentine', 'Malinda', '1936606035', 'Husband', '1199102135');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Chelsy', 'Silbermann', 'Tony', '2051479288', 'Father', '4582467137');
insert into Person (FirstName, LastName, EmergencyContactName, EmergencyContactNumber, EmergencyContactRelation, BankAccNo) values ('Justen', 'MacKeogh', 'Jerald', '2682643920', 'Guardian', '8783853272');

--listed in assignment doc
insert into Skill (SkillName) values ('carpentry');
insert into Skill (SkillName) values ('Plumbing');
insert into Skill (SkillName) values ('electrical');

    --Assumption only 9 Buildings to hold 45 apartments, 5 apartments per building
insert into Building (Address, Postcode) values ('78 Malone Road', 'BT9 5BW');
insert into Building (Address, Postcode) values ('1 Mc Clintock St', 'BT2 7GL');
insert into Building (Address, Postcode) values ('8 College St', 'BT1 6DS');
insert into Building (Address, Postcode) values ('78 Malone Road', 'BT9 5BW');
insert into Building (Address, Postcode) values ('1 Mc Clintock St', 'BT2 7GL');
insert into Building (Address, Postcode) values ('8 College St', 'BT1 6DS');
insert into Building (Address, Postcode) values ('78 Malone Road', 'BT9 5BW');
insert into Building (Address, Postcode) values ('1 Mc Clintock St', 'BT2 7GL');
insert into Building (Address, Postcode) values ('8 College St', 'BT1 6DS');

--Each apartment holds 5 people, 45 apartments for 225 people, each apartment is unique to building only
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 8, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 10, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 9, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 6, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 6, 6, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 9, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 8, 5, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 2, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 10, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 6, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 9, 5, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 9, 5, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 5, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 10, 5, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 5, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 7, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 5, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 10, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 9, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 5, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 6, 2, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 10, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 10, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 5, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 7, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 6, 5, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 5, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 7, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 7, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 9, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 5, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 7, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 9, 2, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 9, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 7, 8, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 9, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 5, 8, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 10, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 6, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 9, 3, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 8, 2, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 10, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 7, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 7, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 8, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 9, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 8, 2, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 7, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 5, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 9, 5, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 5, 5, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 9, 2, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 6, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 8, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 7, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 6, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 5, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 6, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 8, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 7, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 10, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 9, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 7, 10, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 7, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 6, 3, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 10, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 9, 4, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 5, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 6, 4, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 6, 9, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 5, 10, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 10, 5, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 7, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 8, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 9, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 7, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 9, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 10, 2, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 6, 10, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 5, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 9, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 6, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 6, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 5, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 9, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 5, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 9, 3, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 10, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 6, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 5, 3, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 7, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 8, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 9, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 8, 8, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 10, 5, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 5, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 8, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 10, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 8, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 7, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 6, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 5, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 10, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 6, 6, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 9, 2, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 5, 4, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 4, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 5, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 9, 8, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 5, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 6, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 8, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 5, 9, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 6, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 7, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 6, 8, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 5, 8, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 10, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 9, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 6, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 10, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 5, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 7, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 10, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 9, 3, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 8, 2, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 9, 6, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 8, 5, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 9, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 6, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 6, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 10, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 6, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 5, 5, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 10, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 3, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 6, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 8, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 7, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 9, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 8, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 10, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 10, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 10, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 8, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 6, 9, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 10, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 6, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 6, 2, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 8, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 5, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 8, 3, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 10, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 10, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 6, 8, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 10, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 7, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 8, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 7, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 9, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 7, 8, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 10, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 10, 6, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 10, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 9, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 7, 4, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 9, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 9, 6, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 10, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 9, 4, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 6, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 9, 9, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 9, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 7, 9, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 7, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 6, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 5, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 8, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 8, 9, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 9, 5, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 7, 9, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 9, 5, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 9, 8, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 6, 4, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 5, 7, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 7, 3, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 10, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 5, 3, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 7, 3, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 8, 5, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 6, 2, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 8, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 7, 4, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 10, 4, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 9, 2, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 9, 7, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 5, 7, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 9, 6, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 10, 8, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (1, 10, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (2, 7, 6, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (3, 5, 2, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (4, 5, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (5, 8, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (6, 10, 10, 15);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (7, 7, 10, 10);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (8, 5, 10, 30);
insert into Apartment (AptNo, Bedrooms, Bathrooms, TotalArea) values (9, 6, 6, 15);

insert into ApartmentBuilding (AptID, BuildingID) values (1, 1);
insert into ApartmentBuilding (AptID, BuildingID) values (2, 1);
insert into ApartmentBuilding (AptID, BuildingID) values (3, 1);
insert into ApartmentBuilding (AptID, BuildingID) values (4, 1);
insert into ApartmentBuilding (AptID, BuildingID) values (5, 1);
insert into ApartmentBuilding (AptID, BuildingID) values (6, 2);
insert into ApartmentBuilding (AptID, BuildingID) values (7, 2);
insert into ApartmentBuilding (AptID, BuildingID) values (8, 2);
insert into ApartmentBuilding (AptID, BuildingID) values (9, 2);
insert into ApartmentBuilding (AptID, BuildingID) values (10, 2);
insert into ApartmentBuilding (AptID, BuildingID) values (11, 3);
insert into ApartmentBuilding (AptID, BuildingID) values (12, 3);
insert into ApartmentBuilding (AptID, BuildingID) values (13, 3);
insert into ApartmentBuilding (AptID, BuildingID) values (14, 3);
insert into ApartmentBuilding (AptID, BuildingID) values (15, 3);
insert into ApartmentBuilding (AptID, BuildingID) values (16, 4);
insert into ApartmentBuilding (AptID, BuildingID) values (17, 4);
insert into ApartmentBuilding (AptID, BuildingID) values (18, 4);
insert into ApartmentBuilding (AptID, BuildingID) values (19, 4);
insert into ApartmentBuilding (AptID, BuildingID) values (20, 4);
insert into ApartmentBuilding (AptID, BuildingID) values (21, 5);
insert into ApartmentBuilding (AptID, BuildingID) values (22, 5);
insert into ApartmentBuilding (AptID, BuildingID) values (23, 5);
insert into ApartmentBuilding (AptID, BuildingID) values (24, 5);
insert into ApartmentBuilding (AptID, BuildingID) values (25, 5);
insert into ApartmentBuilding (AptID, BuildingID) values (26, 6);
insert into ApartmentBuilding (AptID, BuildingID) values (27, 6);
insert into ApartmentBuilding (AptID, BuildingID) values (28, 6);
insert into ApartmentBuilding (AptID, BuildingID) values (29, 6);
insert into ApartmentBuilding (AptID, BuildingID) values (30, 6);
insert into ApartmentBuilding (AptID, BuildingID) values (31, 7);
insert into ApartmentBuilding (AptID, BuildingID) values (32, 7);
insert into ApartmentBuilding (AptID, BuildingID) values (33, 7);
insert into ApartmentBuilding (AptID, BuildingID) values (34, 7);
insert into ApartmentBuilding (AptID, BuildingID) values (35, 7);
insert into ApartmentBuilding (AptID, BuildingID) values (36, 8);
insert into ApartmentBuilding (AptID, BuildingID) values (37, 8);
insert into ApartmentBuilding (AptID, BuildingID) values (38, 8);
insert into ApartmentBuilding (AptID, BuildingID) values (39, 8);
insert into ApartmentBuilding (AptID, BuildingID) values (40, 8);
insert into ApartmentBuilding (AptID, BuildingID) values (41, 9);
insert into ApartmentBuilding (AptID, BuildingID) values (42, 9);
insert into ApartmentBuilding (AptID, BuildingID) values (43, 9);
insert into ApartmentBuilding (AptID, BuildingID) values (44, 9);
insert into ApartmentBuilding (AptID, BuildingID) values (45, 9);

insert into Lease (AptID, StartDate, Duration, Rent) values (1, '01/09/17', 1, 113.72);
insert into Lease (AptID, StartDate, Duration, Rent) values (2, '01/09/18', 1, 106.31);
insert into Lease (AptID, StartDate, Duration, Rent) values (3, '01/09/18', 2, 93.86);
insert into Lease (AptID, StartDate, Duration, Rent) values (4, '01/09/18', 2, 118.31);
insert into Lease (AptID, StartDate, Duration, Rent) values (5, '01/09/17', 2, 91.84);
insert into Lease (AptID, StartDate, Duration, Rent) values (6, '01/09/17', 2, 106.88);
insert into Lease (AptID, StartDate, Duration, Rent) values (7, '01/09/17', 2, 96.18);
insert into Lease (AptID, StartDate, Duration, Rent) values (8, '01/09/17', 3, 111.76);
insert into Lease (AptID, StartDate, Duration, Rent) values (9, '01/09/17', 1, 98.12);
insert into Lease (AptID, StartDate, Duration, Rent) values (10, '01/09/17', 3, 114.3);
insert into Lease (AptID, StartDate, Duration, Rent) values (11, '01/09/17', 3, 103.87);
insert into Lease (AptID, StartDate, Duration, Rent) values (12, '01/09/19', 3, 95.0);
insert into Lease (AptID, StartDate, Duration, Rent) values (13, '01/09/17', 2, 123.6);
insert into Lease (AptID, StartDate, Duration, Rent) values (14, '01/09/18', 1, 117.06);
insert into Lease (AptID, StartDate, Duration, Rent) values (15, '01/09/18', 2, 93.41);
insert into Lease (AptID, StartDate, Duration, Rent) values (16, '01/09/19', 2, 106.95);
insert into Lease (AptID, StartDate, Duration, Rent) values (17, '01/09/17', 2, 118.56);
insert into Lease (AptID, StartDate, Duration, Rent) values (18, '01/09/18', 3, 104.73);
insert into Lease (AptID, StartDate, Duration, Rent) values (19, '01/09/19', 2, 112.78);
insert into Lease (AptID, StartDate, Duration, Rent) values (20, '01/09/19', 3, 114.55);
insert into Lease (AptID, StartDate, Duration, Rent) values (21, '01/09/17', 1, 120.33);
insert into Lease (AptID, StartDate, Duration, Rent) values (22, '01/09/17', 3, 109.77);
insert into Lease (AptID, StartDate, Duration, Rent) values (23, '01/09/17', 1, 97.64);
insert into Lease (AptID, StartDate, Duration, Rent) values (24, '01/09/18', 3, 109.35);
insert into Lease (AptID, StartDate, Duration, Rent) values (25, '01/09/17', 2, 101.19);
insert into Lease (AptID, StartDate, Duration, Rent) values (26, '01/09/19', 2, 105.3);
insert into Lease (AptID, StartDate, Duration, Rent) values (27, '01/09/18', 3, 94.32);
insert into Lease (AptID, StartDate, Duration, Rent) values (28, '01/09/18', 1, 96.61);
insert into Lease (AptID, StartDate, Duration, Rent) values (29, '01/09/19', 1, 104.6);
insert into Lease (AptID, StartDate, Duration, Rent) values (30, '01/09/19', 2, 104.98);
insert into Lease (AptID, StartDate, Duration, Rent) values (31, '01/09/19', 3, 94.2);
insert into Lease (AptID, StartDate, Duration, Rent) values (32, '01/09/17', 2, 98.45);
insert into Lease (AptID, StartDate, Duration, Rent) values (33, '01/09/18', 3, 95.48);
insert into Lease (AptID, StartDate, Duration, Rent) values (34, '01/09/18', 1, 100.71);
insert into Lease (AptID, StartDate, Duration, Rent) values (35, '01/09/17', 1, 127.01);
insert into Lease (AptID, StartDate, Duration, Rent) values (36, '01/09/19', 2, 116.61);
insert into Lease (AptID, StartDate, Duration, Rent) values (37, '01/09/17', 1, 126.79);
insert into Lease (AptID, StartDate, Duration, Rent) values (38, '01/09/18', 3, 123.6);
insert into Lease (AptID, StartDate, Duration, Rent) values (39, '01/09/17', 1, 113.81);
insert into Lease (AptID, StartDate, Duration, Rent) values (40, '01/09/17', 1, 100.58);
insert into Lease (AptID, StartDate, Duration, Rent) values (41, '01/09/17', 3, 111.15);
insert into Lease (AptID, StartDate, Duration, Rent) values (42, '01/09/18', 3, 113.78);
insert into Lease (AptID, StartDate, Duration, Rent) values (43, '01/09/19', 2, 102.05);
insert into Lease (AptID, StartDate, Duration, Rent) values (44, '01/09/19', 3, 98.85);
insert into Lease (AptID, StartDate, Duration, Rent) values (45, '01/09/19', 3, 123.0);











